title = "Sandboxer"

gitSourceBranch = "main"
changelog = true
classOrder = [
    "Sandboxer",
    "InstanceSandboxer",
    "InstanceList",
    "Config"
]

[docusaurus]
url = "https://littlebitsman.dev"
baseUrl = "/sandboxer"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright Â© 2026 littleBitsman. Docs built with Moonwave and Docusaurus"
