name: Run Tests

on:
  push:
    branches:
      - main
      - rbx-tests
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/test.yml'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: luau-execution-session
      cancel-in-progress: false

    steps:
    - name: Checkout Rust builder
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: rbx-tests

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo run --release # the binary runs tests using Luau execution sessions
      env: 
        ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
    - name: Upload test.rbxm as artifact
      uses: actions/upload-artifact@v5
      with:
        name: test.rbxm
        path: test.rbxm
        if-no-files-found: warn
